#! /bin/bash

CONTAINER_NAME="monitor-server"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
if [ -d "./logs" ];then
	sudo rm -fr ./logs/*
fi

docker run -d \
            -v $(pwd)/logs:/var/log/supervisor \
            -p 8080:80 \
            -p 8081:81 \
            -p 8082:8082 \
            -p 8125:8125/udp \
            -p 8126:8126 \
            --name $CONTAINER_NAME kamon/grafana_graphite
